[workspace]
members = [
    "client",
    "server",
    "shared",
    "demo/server",
    "demo/client/app",
    "demo/client/wasm_bindgen",
    "demo/client/miniquad",
    "demo/dev_http_server"
    ]